import { expect, test, type Page } from '@playwright/test'
import { loginViaForm, setupApiMocks } from './api-mock'

async function openTools(page: Page): Promise<void> {
  await loginViaForm(page)
  await page.goto('/agent/tools')
  await expect(page.getByRole('heading', { name: '工具控制中心' })).toBeVisible()
}

test.describe('Tool Control Center', () => {
  test('renders the catalog, connections, MCP, node grants, and execution timeline', async ({
    page,
  }) => {
    await openTools(page)

    await expect(page.getByText('yuanai.web.search')).toBeVisible()
    await expect(page.getByText('只读')).toBeVisible()

    await page.getByRole('button', { name: '连接' }).click()
    await expect(page.getByText('Docs MCP HTTP')).toBeVisible()

    await page.getByRole('button', { name: 'MCP' }).click()
    await expect(page.getByText('Docs MCP', { exact: true })).toBeVisible()
    await expect(page.getByText('尚未发现 schema')).toBeVisible()
    await page.getByRole('button', { name: '重新发现' }).click()
    await expect(page.getByLabel('search_docs')).toBeVisible()
    await page.getByLabel('search_docs').check()
    await page.getByRole('button', { name: '启用所选工具' }).click()
    await expect(page.locator('.tools-card').filter({ hasText: 'Docs MCP' })).toContainText(
      '已启用工具: search_docs'
    )

    await page.getByRole('button', { name: '执行节点' }).click()
    await expect(page.getByText('Office Desktop')).toBeVisible()
    await expect(page.getByText('Agent workspace')).toBeVisible()
    await page.getByLabel('显示名称').fill('Pairing Desktop')
    await page.getByLabel('版本').fill('0.1.0')
    await page.getByRole('button', { name: '生成配对码' }).click()
    await expect(page.getByText('pairing-code-e2e')).toBeVisible()

    await page.getByRole('button', { name: '执行记录' }).click()
    await expect(page.getByText('结果: 找到 3 条结果', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: '取消' }).click()
    await expect(page.getByText('已取消')).toBeVisible()
  })

  test('approves a pending request and provides an Artifact preview and download', async ({
    page,
  }) => {
    await openTools(page)

    await page.getByRole('button', { name: 'Artifact' }).click()
    await expect(page.getByText(/"Generated by tool runtime"/)).toBeVisible()
    const download = page.getByRole('link', { name: '下载' })
    await expect(download).toHaveAttribute('download', '')
    const downloadPromise = page.waitForEvent('download')
    await download.click()
    expect((await downloadPromise).suggestedFilename()).toBe('report.md')

    await page.getByRole('button', { name: '审批' }).click()
    await expect(page.getByText('在 Agent 工作区生成 report.md')).toBeVisible()
    await page.getByRole('button', { name: '批准' }).click()
    await expect(page.getByText('已批准')).toBeVisible()
    await expect(page.getByRole('button', { name: '批准' })).toHaveCount(0)
  })

  test('renders empty and failed API states distinctly', async ({ page }) => {
    await setupApiMocks(page, { toolCenterState: 'empty' })
    await page.goto('/login')
    await page.locator('.a-tab:nth-child(2)').click()
    await page.locator('input[type="email"]').fill('demo@yuanai.dev')
    await page.locator('input[type="password"]').fill('Demo1234!')
    await page.getByRole('button', { name: '登录', exact: true }).click()
    await page.waitForURL(/\/chat/)
    await page.goto('/agent/tools')
    await page.getByRole('button', { name: '连接' }).click()
    await expect(page.getByText('还没有工具连接')).toBeVisible()
    await page.getByRole('button', { name: 'MCP' }).click()
    await expect(page.getByText('还没有 MCP Server')).toBeVisible()
    await page.getByRole('button', { name: '执行节点' }).click()
    await expect(page.getByText('还没有配对的执行节点')).toBeVisible()
    await page.getByRole('button', { name: '执行记录' }).click()
    await expect(page.getByText('还没有工具执行记录')).toBeVisible()
    await page.getByRole('button', { name: 'Artifact' }).click()
    await expect(page.getByText('还没有 Artifact')).toBeVisible()
    await page.getByRole('button', { name: '审批' }).click()
    await expect(page.getByText('没有等待处理的审批')).toBeVisible()

    await page.unrouteAll({ behavior: 'wait' })
    await setupApiMocks(page, { toolCenterState: 'failure' })
    await page.reload()
    await expect(page.getByText('操作失败，请重试')).toBeVisible()
  })
})
