"""add_thinking_content_to_message

Revision ID: 0e5e89b7b1d8
Revises: c0218f5faa41
Create Date: 2026-07-02 18:35:20.435562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5e89b7b1d8'
down_revision: Union[str, None] = 'c0218f5faa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('thinking_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'thinking_content')
    # ### end Alembic commands ###
